version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  visual-review:
    parameters:
      options:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn chromatic <<parameters.options>> # CHROMATIC_APP_CODE=*** in circleCI context
workflows:
    visual review:
      jobs:
        - visual-review:
            context: example-chromatic-workflow
            options: --exit-zero-on-changes
            filters:
              branches:
                only:
                  - /ui\/.*/
    publish component list:
      jobs:
        - visual-review:
            context: example-chromatic-workflow
            options: --auto-accept-changes
            filters:
              branches:
                only:
                  - develop
                  - master
